### ISSUE TITLE
Error on site

### ISSUE THREAD

**Issue by akamajoris** [pivotal-golang/bytefmt#3]
https://godoc.org/github.com/pivotal-golang/bytefmt
First example:
```bytefmt.ByteSize(100.5*bytefmt.MEGABYE) // "100.5M"```
MEGABYE

**Comment by ematpl** [comment]
Thanks, @akamajoris. Fixed in https://github.com/pivotal-golang/bytefmt/commit/f6365116023dcfc746de43fbc5a1b9e1564c7ddf.

Best,
Eric, CF Runtime Diego PM
